services:
  wayfinder-aprs-gateway:
    image: ghcr.io/kennethbrewer3/wayfinder_aprs_gateway:latest
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    # Uncomment for simulator mode:
    # volumes:
    #   - ./simulator.json:/app/simulator.json:ro
